name: Deploy Dev

on:
  push:
    branches: ["develop"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.TARGET_HOST }}
          username: ${{ secrets.TARGET_USER }}
          key: ${{ secrets.SSH_PRIV_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/unigem-dev/src
            git pull origin develop
